# Generated by Django 4.2.11 on 2026-04-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_alter_issue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="rating",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
